apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: arthur/ftps
        imagePullPolicy: Never
        livenessProbe:
          periodSeconds: 3
          initialDelaySeconds: 60
          exec:
            command:
              - /bin/sh
              - -c
              - ./tmp/live.sh
        readinessProbe:
          exec:
            command:
              - ./tmp/ready.sh
          periodSeconds: 2
          failureThreshold: 30
        env:
          - name: FTP_USER
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: FTP_USER
          - name: FTP_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: FTP_PASSWORD
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
          - containerPort: 21
          - containerPort: 20
          - containerPort: 30020
          - containerPort: 30021
        volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/volume
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
           
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 21
      targetPort: 21
      nodePort: 30025
      protocol: TCP
      name: ftp21
    - port: 20
      targetPort: 20
      protocol: TCP
      nodePort: 30026
      name: ftp20
    - port: 30020
      targetPort: 30020
      nodePort: 30020
      protocol: TCP
      name: ftp30020
    - port: 30021
      targetPort: 30021
      nodePort: 30021
      protocol: TCP
      name: ftp30021