apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql
        image: arthur/mysql
        imagePullPolicy: Never
        livenessProbe:
          periodSeconds: 3
          initialDelaySeconds: 15
          exec:
            command:
              - /bin/sh
              - -c
              - ./tmp/live.sh
        readinessProbe:
          exec:
            command:
              - ./tmp/ready.sh
          periodSeconds: 2
          failureThreshold: 30
        ports:
        - containerPort: 3306
          name: http
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        envFrom:
          - configMapRef:
              name: env-config
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: http