apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: arthur/nginx
        imagePullPolicy: Never
        livenessProbe:
          periodSeconds: 2
          initialDelaySeconds: 10
          exec:
            command:
              - /bin/sh
              - -c
              - ./tmp/live.sh
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: ssl
---  
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: ssl