apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: arthur/phpmyadmin
        imagePullPolicy: Never
        livenessProbe:
          periodSeconds: 3
          initialDelaySeconds: 60
          exec:
            command:
              - /bin/sh
              - -c
              - ./tmp/live.sh
        readinessProbe:
          httpGet:
            path: /
            port: http
          periodSeconds: 2
          failureThreshold: 30
        ports:
        - name: http
          containerPort: 5000
        envFrom:
          - configMapRef:
              name: env-config
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
---         
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http