<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.2 setup script
 * Date: Thu, 03 Jun 2021 09:22:22 +0000
 */

/* Servers configuration */
    $i = 0;

    /**
     * First server
     */
    $i++;
    /* Authentication type */
    $cfg['Servers'][$i]['auth_type'] = 'cookie';
    /* Server parameters */
    $cfg['Servers'][$i]['host'] = 'mysql';
    $cfg['Servers'][$i]['compress'] = false;
    $cfg['PmaAbsoluteUri'] = './';
    

?>